apiVersion: v1
kind: Pod
metadata:
  name: apiclient-hw
  labels:
    app: apiclient-hw
spec:
  containers:
  - name: apimocks
    image: localhost:5000/apimocks:1.0
  - name: flow
    image: localhost:5000/flow:1.0
    ports:
    - containerPort: 3100
