apiVersion: v1
kind: Pod
metadata:
  name: apiclient-hw
  labels:
    app: apiclient-hw
spec:
  containers:
  - name: apimocks
    image: localhost:3000
  - name: flow
    image: localhost:3100
    ports:
    - containerPort: 3100
